theme = "hugo-theme-novela"
baseURL = "http://ids.works"
languageCode = "en-us"
paginate = 4
enableRobotsTXT = true
googleAnalytics = "UA-166935370-2"
title = "Dmitrii Storozhenko"
  [taxonomies]
      tag = "tags"
      author = "Dmitrii Storozhenko"
      preserveTaxonomyNames = true