baseURL: "https://ids.works"
languageCode: "en-us"
title: "Making the right data-driven decisions."
pygmentsstyle: 'monokai'
paginate: 4
social:
  twitter: "https://twitter.com/dbs700"
  instagram: "#"
  linkedin: "https://www.linkedin.com/in/dmitrii-storozhenko/"
  youtube: "#"
taxonomies:
  author: authors
